{
  "properties" : { },
  "id" : "1c04ead82c3d40a3af1f549680a33e03",
  "script" : null,
  "groupId" : "9c416fafc8b24dee85b6572562b05b64",
  "name" : "船企用户注册",
  "createTime" : 1689908629921,
  "updateTime" : 1693552389050,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/registerCompanyUser",
  "method" : "GET",
  "parameters" : [ ],
  "options" : [ ],
  "requestBody" : "",
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : null,
  "description" : null,
  "requestBodyDefinition" : null,
  "responseBodyDefinition" : null
}
================================
return 'Hello magic-api'